### ISSUE TITLE
Does not work in Chrome 56

### ISSUE THREAD

**Issue by niutech** [bernhardc/open-in-intellij#1]
I configured the host `localhost:8080` in the options, but still there is no _Open in IntelliJ_ item in the context menu in Chrome 56:

![intellij](https://cloud.githubusercontent.com/assets/384997/22736115/ffeb2e5e-edfc-11e6-8ce1-eb92e8e607b2.png)

**Comment by bernhardc** [comment]
I updated the Readme for this project with more detailed installation and troubleshooting tips. Hope this helps.

**Comment by bernhardc** [comment]
Also the host name in the options is for the IntelliJ REST API, not for your web project. In most cases the default (http://localhost:63342) doesn't need to be changed.
