### ISSUE TITLE
Root paths are not working

### ISSUE THREAD

**Issue by ConeyIsland** [bernhardc/open-in-intellij#3]
I think settings not working or smth wrong; the link is still 
`http://localhost:63342/api/file?file=/css/main.css&line=17`
but should be
`http://localhost:63342/api/file?file=src/css/main.css&line=17`
![screenshot from 2018-01-25 02-33-32](https://user-images.githubusercontent.com/4426233/35362917-7b701d3e-0178-11e8-91df-ba23a2641fe9.png)

If it matters my soft are: 
Chromium Version 63.0.3239.132 (Official Build) Built on Ubuntu, running on Ubuntu 16.04 (64-bit)
Webstorm 2017.3.3

**Comment by bernhardc** [comment]
Thanks for reporting! I fixed the issue and published the changes as v0.6 to the Chrome Web Store. 
Is it now working for you?

**Comment by MonoStas** [comment]
Yeah, it works with manual settings now, but not by default beacause of unnecessary slash. Maybe they changed smth in this case. Look at screen
your root 
`http://localhost:63342/api/file?file=/css/main.css&line=104`
but in real life it works only without slash
`http://localhost:63342/api/file?file=css/main.css&line=104`
![image](https://user-images.githubusercontent.com/4426233/36040856-c99fb2a6-0dd7-11e8-9b5d-13b490ce9835.png)
I think you should delete unnecessary slash to fix this issue too. But if I use settings - it's now OK, thank you so much!

**Comment by bernhardc** [comment]
I just released version 0.8. Please report of the issue is fixed now. Thanks! 🙂

**Comment by ConeyIsland** [comment]
> I just released version 0.8. Please report of the issue is fixed now. Thanks!

It works, thanks.
