### ISSUE TITLE
Not working when path starts with /

### ISSUE THREAD

**Issue by filipenevola** [bernhardc/open-in-intellij#4]
Hello, great extension, thank you.

In my case, a Meteor project, it was not working on WebStorm because the paths were starting with `/`, just removing the `/` make it work.

I need to transform
`destination resource path: /imports/ui/components/general/SelectField.js`
in
`destination resource path: imports/ui/components/general/SelectField.js`

I have created a fork with this change, if you think that is affecting others I can create a PR with this commit
https://github.com/filipenevola/open-in-intellij/commit/58072559fcd59503831db1342387ff20cf32eb92

Again, great extension, thank you!

**Comment by MonoStas** [comment]
Did you fixed this bug?
https://github.com/bernhardc/open-in-intellij/issues/3

**Comment by filipenevola** [comment]
Hello @MonoStas, maybe, please clone or download my fork and load it on your Chrome `Load unpacked` to check.

**Comment by MonoStas** [comment]
> Hello @MonoStas, maybe, please clone or download my fork and load it on your Chrome `Load unpacked` to check.

Yeah, it now works. Make a pull request, please, and we can close two issues.

**Comment by filipenevola** [comment]
@MonoStas done https://github.com/bernhardc/open-in-intellij/pull/5

**Comment by bernhardc** [comment]
This is a duplicate of #3 3. Closing this issue.
