### ISSUE TITLE
Request for config help

### ISSUE THREAD

**Issue by tmtron** [bernhardc/open-in-intellij#6]
I cannot make the extension work for some reason.

my **root path mapping config** (and explanation why):
* in chrome dev-tools when I hoover over an open file, I see the link that starts with webpack:  
  e.g. `webpack:///./src/app/domain/dashboard/dashboard.component.ts`
![image](https://user-images.githubusercontent.com/20422904/60394895-5694c480-9b2b-11e9-8864-45c47a2debe2.png)
* when I open the file in intelliJ directly and copy the relative path, it is:  
  `apps/client/src/app/domain/dashboard/dashboard.component.ts`
* when I open my application in the browser I use this URL: `http://localhost:5600/`
* so I think the correct **root path mapping** should be  
  `localhost` -> `apps/client/`
  * since this did not work I have also added the same rel. path for `http://localhost:5600` and `localhost:5600` (not sure, if this is needed) - but also didn't work

The **issue**: when I right-click on the file-tab and select `Open using Open in IntelliJ` from the pop-up menu, nothing happens:
![image](https://user-images.githubusercontent.com/20422904/60394928-09652280-9b2c-11e9-8e92-e6aa4f557665.png)
there is not even a message in the console window.

Using the **URL directly works**: when I open a new tab in Chrome and enter one of the following URLs, it works (i.e. the file is opened in IntelliJ):
* `http://localhost:63342/api/file?file=apps/client/src/app/domain/dashboard/dashboard.component.ts`
* `http://localhost:63342/api/file?file=apps/client/./src/app/domain/dashboard/dashboard.component.ts`
(note the `/./` after `apps/client`
* Note: even in this working cases I see no info on the javascript console (e.g. I open the chrome dev tools and then press F5 to send the URL request again)
* when I send a wrong URL : e.g. `http://localhost:63342/api/file?file=/src/app/domain/dashboard/dashboard.component.ts`  nothing happens

Version info:
* chrome: Version 75.0.3770.100 
* Open-in-intellij: 0.8.1

I suppose that the extension is sending a wrong file-path or nothing at all. But since I see no debug messages in the console, I am not sure:   

Any idea why there is no debug output or how I could activate it?

**Comment by bernie43** [comment]
There are debug messages, you just have to inspect the devtools window. This is the section from the Readme:

> Make sure the Devtools are undocked into a separate window (open the three-dot Chrome Devtools settings menu and select the first icon from "Dock side"). Then inspect the current DevTools window by pressing Ctrl+Shift+I (Windows) or Option+Command+I (Mac). Yes, you can actually inspect the DevTools window itself. Switch to the console tab, there will be debug messages from this extension like 'Open In IntelliJ - received open resource event'. This may help with your troubleshooting process.

Your path mapping looks good, so actually it should be working.


> Note: even in this working cases I see no info on the javascript console (e.g. I open the chrome dev tools and then press F5 to send the URL request again)

This will never output anything, since you're just sending a request to the local IntelliJ server.

**Comment by tmtron** [comment]
Thanks for the  response, I misunderstood the docs - I thought that the debug messages would directly end up on the java-script console of the application debugging session.

So this is how I get the debug messages:

- In the main window (A), I load my application (1)
- then I press CTRL-SHIFT-I to bring up the app-dev-tools window (B)
- now in window (B) I press CTRL-SHIFT-I again to open another dev-tools windows (C)
- then I go to window (B), open a source file, right-click on the tab-sheet of the file (2) and select 'Open using Open In IntelliJ' from the pop-up menu (3)
- and then I will see the debug messages in the console of window (C)
![image](https://user-images.githubusercontent.com/20422904/60568277-b3cb8880-9d6c-11e9-9afe-79866ad6c93b.png)

so from the debug message, it seems that my mappings are not applied, as expected
Here is the debug-output
```
Open In IntelliJ - received open resource event: webpack:///./src/app/domain/dashboard/dashboard.component.ts 1
openinide.js:211 Open In IntelliJ - destination resource path: ./src/app/domain/dashboard/dashboard.component.ts
openinide.js:68 Open In IntelliJ - calling IntelliJ API: http://localhost:63342/api/file?file=./src/app/domain/dashboard/dashboard.component.ts&line=1
openinide.js:80 Open In IntelliJ - IntelliJ API response: HTTP 200 OK - file opened in IntelliJ successfully
```
I can see that the requested file-path is `file=./src/app/domain/dashboard/dashboard.component.ts`.
Here are my mappings:
![image](https://user-images.githubusercontent.com/20422904/60568776-15402700-9d6e-11e9-80d3-b6454d7dc5ba.png)

With those mappings, I'd expect the requested path to be `file=apps/client/./src/app/domain/dashboard/dashboard.component.ts`.  
And this works, when I enter the URL directly in the browser main window.

Any ideas, what could be wrong?

**Comment by tmtron** [comment]
not sure why, but it works now (with the same settings): maybe a restart, clear cache, or something like that helped
